# Generated by Django 4.2.3 on 2023-07-22 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("creators", "0005_creator_channel_registered_date_and_more"),
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YoutubeReports",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("job_id", models.CharField(max_length=255)),
                ("report_url", models.CharField(max_length=255)),
                ("report_type", models.CharField(max_length=255)),
                ("report_name", models.CharField(max_length=255)),
                (
                    "owner",
                    models.OneToOneField(
                        db_column="owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_reports",
                        to="creators.creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Youtube Report",
                "verbose_name_plural": "Youtube Reports",
                "db_table": "youtube_reports",
            },
        ),
        migrations.CreateModel(
            name="YoutubeCredential",
            fields=[
                (
                    "account_id",
                    models.OneToOneField(
                        db_column="account_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_uri", models.TextField()),
                ("client_id", models.TextField()),
                ("client_secret", models.TextField()),
                ("scope", models.TextField()),
                (
                    "creator_id",
                    models.ForeignKey(
                        db_column="creator_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_credentials",
                        to="creators.creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Youtube Credential",
                "verbose_name_plural": "Youtube Credentials",
                "db_table": "youtube_credentials",
            },
        ),
        migrations.CreateModel(
            name="YoutubeChannelBasic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("channel_id", models.CharField(max_length=100)),
                ("channel_name", models.CharField(max_length=100)),
                ("channel_handle", models.CharField(max_length=100)),
                ("video_id", models.CharField(blank=True, max_length=100, null=True)),
                ("subscribed_status", models.BooleanField(default=False)),
                ("country_code", models.CharField(max_length=4)),
                ("views", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("dislikes", models.IntegerField(default=0)),
                ("shares", models.IntegerField(default=0)),
                ("watch_time_minutes", models.FloatField(default=0)),
                ("average_view_duration_seconds", models.FloatField(default=0)),
                ("average_view_percentage", models.FloatField(default=0)),
                ("susbscribers_gained", models.IntegerField(default=0)),
                ("subscribers_lost", models.IntegerField(default=0)),
                ("annotation_impressions", models.IntegerField(default=0)),
                ("annotation_clicks", models.IntegerField(default=0)),
                ("annotation_click_through_rate", models.IntegerField(default=0)),
                ("card_impressions", models.IntegerField(default=0)),
                ("card_clicks", models.IntegerField(default=0)),
                ("card_click_through_rate", models.IntegerField(default=0)),
                ("videos_added_to_playlists", models.IntegerField(default=0)),
                ("videos_removed_from_playlists", models.IntegerField(default=0)),
                ("red_views", models.IntegerField(default=0)),
                ("red_watch_time_minutes", models.FloatField(default=0)),
                (
                    "creator_id",
                    models.ForeignKey(
                        db_column="creator_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_basics",
                        to="creators.creator",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_basics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Youtube Channel Basic",
                "verbose_name_plural": "Youtube Channel Basics",
                "db_table": "youtube_channel_basics",
            },
        ),
    ]
