# Generated by Django 4.2.3 on 2023-07-22 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("creators", "0004_delete_channelbasic"),
        ("youtube_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubereports",
            name="date",
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="youtubereports",
            name="owner",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="youtubereports",
            name="report_name",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="youtubereports",
            name="report_type",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="youtubereports",
            name="report_url",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="youtubereports",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="YoutubeChannelBasic",
            fields=[
                (
                    "creator_id",
                    models.OneToOneField(
                        db_column="creator_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="creator_basics",
                        serialize=False,
                        to="creators.creator",
                    ),
                ),
                ("date", models.DateField()),
                ("channel_id", models.CharField(max_length=100)),
                ("channel_name", models.CharField(max_length=100)),
                ("channel_handle", models.CharField(max_length=100)),
                ("video_id", models.CharField(max_length=100)),
                ("subscribed_status", models.PositiveIntegerField(default=0)),
                ("country_code", models.CharField(max_length=4)),
                ("views", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("dislikes", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("watch_time_minutes", models.PositiveIntegerField(default=0)),
                (
                    "average_view_duration_seconds",
                    models.PositiveIntegerField(default=0),
                ),
                ("average_view_percentage", models.PositiveIntegerField(default=0)),
                ("susbscribers_gained", models.PositiveIntegerField(default=0)),
                ("subscribers_lost", models.PositiveIntegerField(default=0)),
                ("annotation_impressions", models.PositiveIntegerField(default=0)),
                ("annotation_clicks", models.PositiveIntegerField(default=0)),
                (
                    "annotation_click_through_rate",
                    models.PositiveIntegerField(default=0),
                ),
                ("card_impressions", models.PositiveIntegerField(default=0)),
                ("card_clicks", models.PositiveIntegerField(default=0)),
                ("card_click_through_rate", models.PositiveIntegerField(default=0)),
                ("videos_added_to_playlists", models.PositiveIntegerField(default=0)),
                (
                    "videos_removed_from_playlists",
                    models.PositiveIntegerField(default=0),
                ),
                ("red_views", models.PositiveIntegerField(default=0)),
                ("red_watch_time_minutes", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_basics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Youtube Channel Basic",
                "verbose_name_plural": "Youtube Channel Basics",
                "db_table": "youtube_channel_basics",
            },
        ),
    ]
