# Generated by Django 4.2.3 on 2023-07-23 07:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("youtube_analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="youtubechannelbasic",
            old_name="average_view_percentage",
            new_name="average_view_duration_percentage",
        ),
        migrations.RenameField(
            model_name="youtubechannelbasic",
            old_name="susbscribers_gained",
            new_name="subscribers_gained",
        ),
    ]
