# Generated by Django 4.2.3 on 2023-07-10 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("youtube_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="youtubecredential",
            options={
                "verbose_name": "Youtube Credential",
                "verbose_name_plural": "Youtube Credentials",
            },
        ),
        migrations.AlterModelTable(
            name="youtubecredential",
            table="youtube_credential",
        ),
    ]
