# Generated by Django 4.2.3 on 2023-07-23 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0005_creator_channel_registered_date_and_more"),
        (
            "youtube_analytics",
            "0002_rename_average_view_percentage_youtubechannelbasic_average_view_duration_percentage_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="YoutubeReportingJob",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job_id", models.CharField(max_length=255)),
                ("job_type", models.CharField(max_length=255)),
                ("job_name", models.CharField(max_length=255)),
                (
                    "owner",
                    models.OneToOneField(
                        db_column="owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_reporting_job",
                        to="creators.creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Youtube Reporting Job",
                "verbose_name_plural": "Youtube Reporting Jobs",
                "db_table": "youtube_reporting_job",
            },
        ),
        migrations.DeleteModel(
            name="YoutubeReports",
        ),
    ]
