# Generated by Django 4.2.3 on 2023-07-22 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("youtube_analytics", "0002_youtubereports_date_youtubereports_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="youtubecredential",
            table="youtube_credentials",
        ),
    ]
