# Generated by Django 4.2.3 on 2023-07-11 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Creator",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("earnings", models.PositiveIntegerField(default=0)),
                ("channel_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "channel_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "channel_handle",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("channel_verified", models.BooleanField(default=False)),
                (
                    "account_id",
                    models.OneToOneField(
                        db_column="account_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Creator",
                "verbose_name_plural": "Creators",
                "db_table": "creators",
            },
        ),
    ]
