# Generated by Django 4.2.3 on 2023-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="channel_handle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="creator",
            name="channel_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="creator",
            name="channel_verified",
            field=models.BooleanField(default=False),
        ),
    ]
