# Generated by Django 4.2.3 on 2023-07-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0004_delete_channelbasic"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="channel_registered_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creator",
            name="channel_report_generated",
            field=models.BooleanField(default=False),
        ),
    ]
