# Generated by Django 4.2.3 on 2023-07-03 13:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "brand_name",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(100)]
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(100)]
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="campaigns/thumbnails/"
                    ),
                ),
                (
                    "category",
                    models.TextField(
                        choices=[
                            ("Fashion", "Fashion"),
                            ("Beauty", "Beauty"),
                            ("Food", "Food"),
                            ("Travel", "Travel"),
                            ("Beverages", "Beverages"),
                        ]
                    ),
                ),
                (
                    "platform",
                    models.TextField(
                        choices=[
                            ("Instagram", "Instagram"),
                            ("Youtube", "Youtube"),
                            ("Tiktok", "Tiktok"),
                        ]
                    ),
                ),
                ("recruit_start_date", models.DateField()),
                ("recruit_end_date", models.DateField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "mission_type",
                    models.TextField(
                        choices=[
                            ("Youtube Video", "Youtube Video"),
                            ("Youtube Shorts", "Youtube Shorts"),
                            ("Post", "Post"),
                            ("Story", "Story"),
                            ("Reel", "Reel"),
                            ("IGTV", "Igtv"),
                            ("Tiktok Video", "Tiktok Video"),
                        ]
                    ),
                ),
                ("reward", models.PositiveIntegerField()),
                (
                    "additional_files",
                    models.FileField(
                        blank=True, null=True, upload_to="campaigns/additional_files/"
                    ),
                ),
                (
                    "username",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(25)]
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                ("modified_at", models.DateTimeField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "db_table": "campaigns",
            },
        ),
    ]
