# Generated by Django 4.2.3 on 2023-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0002_creator_channel_handle_creator_channel_name_and_more"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="username",
        ),
        migrations.AddField(
            model_name="campaign",
            name="approved_creators",
            field=models.ManyToManyField(
                blank=True, related_name="approved_campaigns", to="creators.creator"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_recruited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_recruiting",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="rejected_creators",
            field=models.ManyToManyField(
                blank=True, related_name="rejected_campaigns", to="creators.creator"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="requested_creators",
            field=models.ManyToManyField(
                blank=True, related_name="requested_campaigns", to="creators.creator"
            ),
        ),
    ]
