# Generated by Django 4.2.3 on 2023-08-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
